### ISSUE TITLE
Console error 102-2482

### ISSUE THREAD

**Issue by guill3sm** [PretendoNetwork/.github#16]
While opening miiverse or using the Network, error 102-2482 appears

**Comment by expouic** [comment]
same error +1

**Comment by LeBazarDeBryan** [comment]
same for me

**Comment by Xppp1** [comment]
Same error using cemu version 2.0-29, it pops up for me when pressing the Online button in MK8, with ErrEula box

**Comment by AlexTech01** [comment]
Same error with a Wii U modded with Aroma running Inkay v2.4.0. Miiverse still works but nothing else does.

**Comment by thanone2** [comment]
I get this on Smash Bros on the latest version of Cemu

**Comment by jonbarrow** [comment]
There are no Smash servers

**Comment by thanone2** [comment]
> There are no Smash servers

😢

**Comment by jonbarrow** [comment]
I'm going to close this. 102-2482 is a generic error that means "there is no server for what you requested". Check our website and other repos to see what we currently support.
