### ISSUE TITLE
The cause of 102-2932 on Cemu (Website bug)

### ISSUE THREAD

**Issue by Potenho** [PretendoNetwork/.github#23]
Hi, my server is hosting a Splatfest and a lot of cemu players were experiencing this error in splatoon's lobby. 

![image](https://user-images.githubusercontent.com/60114841/232145161-7ba1aa67-cc8f-4fe1-b64f-3784291ff96f.png)

     It seems that the cause of the error (although the documention says "unknown") is the incorrect value of the parameter
     "AccountPasswordCache" in the account file. It is caused when the user downloads the account files from the website 
     **without** typing their password before pressing "confirm". 

     Here's a picture of how the website currently looks. As you can see, the color of the password input is the same as the window,
     making it impossible to notice it without hovering the mouse over it. 

![image](https://user-images.githubusercontent.com/60114841/232145258-a0c8d722-c6c7-4471-9413-719597808442.png)

     I think this could be fixed by changing the background-color of the password input in the .cs file and not allowing the user to 
     download the files without typing the password. 

     Hopefully this can be fixed as soon as possible to avoid 102-2932!

**Comment by Agggelosio** [comment]
is it fixed now?

**Comment by Potenho** [comment]
It's not.

**Comment by jonbarrow** [comment]
Closing since we no longer offer the ability to download these files
