### ISSUE TITLE
Zelda Wind Waker support?

### ISSUE THREAD

**Issue by lothar-cell** [PretendoNetwork/.github#29]
I haven't seen the game mentioned on the website, does Pretendo support it?

**Comment by burndive** [comment]
I've been playing the game.  Yes, it supports it in that you can send and receive Tingle Bottles.  However, the Tingle Bottles you receive will only be text or drawing posts.  You can still send from your photo album, but it won't be received by other players.  There is (at least currently, as far as I can tell) no support for receiving other players' images in your Tingle Bottles. 

It is nice to have the bottles back, but I miss seeing other players' photos, including ones that help fill out the in-game figurine collection.

**Comment by jonbarrow** [comment]
This is not the correct repository for this issue. If you're having issues with in-game Miiverse features, make an issue on the https://github.com/PretendoNetwork/miiverse-api repository.

**Comment by burndive** [comment]
This has already been done: https://github.com/PretendoNetwork/miiverse-api/issues/36

**Comment by jonbarrow** [comment]
> The issue has already been opened there: [PretendoNetwork/miiverse-api#36](https://github.com/PretendoNetwork/miiverse-api/issues/36)

I am aware. My reply was aimed at @lothar-cell, and was meant as a general warning of where these things should go. Not specifically about this specific game
