### ISSUE TITLE
Error 102-2482 Wii U Chat

### ISSUE THREAD

**Issue by AndreaTheHacker** [PretendoNetwork/.github#33]

**Comment by AndreaTheHacker** [comment]
Please answer

**Comment by DarthArnettJr** [comment]
Try using the beta servers. Wii U Chat hasn't been fully released to the public.

**Comment by catguy323** [comment]
> Try using the beta servers. Wii U Chat hasn't been fully released to the public.

ok that's why

**Comment by thanone2** [comment]
I'm having this problem in wii sports club, any pointers?

**Comment by DarthArnettJr** [comment]
Public or private, it ain't gonna work. Just wait.

**Comment by thanone2** [comment]
I figured out (just like Splatoon) that you have to restart the game a couple times to play, but for Wii sports club, offline.

**Comment by jonbarrow** [comment]
102-2482 means "there are no servers for what you requested". See our website and repos for supported titles. Not all games/apps are available to the public, some are limited to beta testers. Wii U Chat is one of them.
