### ISSUE TITLE
This Nintendo Network ID is already associated with another user on this console.

### ISSUE THREAD

**Issue by SachaKeserovic** [PretendoNetwork/.github#40]
Hello,

I just created a Pretendo account. I used the same PNID as my legacy NNID.

Now I cannot add the Pretendo account on my Wii U, because it says that **_"This Nintendo Network ID is already associated with another user on this console."_**

I also cannot remove my legacy Nintendo Network account because it says that you need to have at least one account.

Am I stuck? I followed the official [Pretendo documentation](https://pretendo.network/docs/install/wiiu) and nowhere does it say that you can't use the same nickname as the one you had on Nintendo Network.

Thanks for your help.

**Comment by jonbarrow** [comment]
> nowhere does it say that you can't use the same nickname as the one you had on Nintendo Network

The docs now mention this, for both the Wii U and 3DS, and have for a while. This was not always the case since I assumed people would understand that of course you cannot link the same username to multiple accounts on the same console

Closing since the docs mention this
