### ISSUE TITLE
Opening Badge Arcade on PNID instead of NNID will nuke your badges.

### ISSUE THREAD

**Issue by benny-dreamly** [PretendoNetwork/.github#52]
Hi there, we've been trying to raise awareness for this issue in the Discord server, but it hasn't gained  much traction. As evidenced by some screenshots and a thread in the support channel, myself and a group of other people have been trying to save as many badges for people as possible. We were hoping to start an archival effort as well, but haven't gotten that far. Just want to save as many people from being victims to this awful thing.

**Comment by benny-dreamly** [comment]
![image](https://github.com/PretendoNetwork/Pretendo/assets/78334662/a5ee251d-9e2a-4151-9467-b48f83b4ab8c)

**Comment by As0mn** [comment]
I would also like to add that a backup of the Badge Arcade save data is pretty much necessary if you wan to transfer your badges to Pretendo or switch back to Nintendo Network with your badges.

**Comment by benny-dreamly** [comment]
To avoid this, you can backup the Nintendo 3DS folder, or the 000014d1 folder in the extdata folder.

**Comment by snoozbuster** [comment]
A PR was opened to add some warnings to the 3ds docs: https://github.com/PretendoNetwork/website/pull/277

I also commented about a potential solution in the nimbus thread

**Comment by jonbarrow** [comment]
Closing since the docs now mention this, and also you can get your badges back by just moving back to NN
