### ISSUE TITLE
003-2101

### ISSUE THREAD

**Issue by KabiPL** [PretendoNetwork/.github#53]
Hello I have a problem because I got error 003-2101 when I want to to something what use internet. I got that error when I am connected to home WI-FI, but when I am connected to WI-FI from phone I don't got that error. Please help me.

**Comment by labibk00** [comment]
I got the same error, fixed by setting DNS to 8.8.8.8 and 8.8.4.4.

**Comment by jonbarrow** [comment]
This is not an issue with our services, please do not use our issue tracker to try and get generic support
