### ISSUE TITLE
Sorry to interrupt.　My request to you.

### ISSUE THREAD

**Issue by DDPhoenix** [PretendoNetwork/.github#56]
Hi! I'm Japanese. Forgive my poor English and the interruption of your work.
I hope that pretendo corresponds to Animal Crossing: New Leaf, please!!!
If you can accommodate this, I couldn't be happier!!!

**Comment by jonbarrow** [comment]
All games are planned for release, they will come with time. Please do not make issues asking for specific games as that clutters up our issue tracker
