### ISSUE TITLE
Will you guys add a 7 days cooldown to male a new account on cemu like wimmfi. Something like when you log on cemu for the First time  without any Wii u dump It Will Say "since this Is a new cemu nand you have to wait 7 days to play(this Is to prevent cheating)"

### ISSUE THREAD

**Issue by antu2010** [PretendoNetwork/.github#57]

**Comment by jonbarrow** [comment]
Please do not make issues with massive titles like this. Titles should be short, use the issue body for the actual content.

To answer your question, probably not. We don't really have a way to detect if requests are coming from Cemu or not.
