### ISSUE TITLE
Updating Pretendo on Console As Instructed
Error Code: 120-9023

### ISSUE THREAD

**Issue by NatsuDragneel808** [PretendoNetwork/.github#58]
Hey, I couldn't find the error code anywhere. Not for the Wii U stock or anything about it on Pretendo. No forums, Google searches etc. As we all know, you can't currently update your information on the Pretendo website, it instructs you to change it from your console instead. However when I attempted to do so I was presented with this 120-9023 error code in which I don't see anything online about its existence at all. Does anyone know what this code means? I'm assuming it's an unreleased error code specifically on pretendo's network. While I do understand Pretendo is still beta (Thank you devs btw. You're amazing) and only a handful of things work, I was just curious. Maybe I'm just the first to get this unknown error.

**Comment by Zapperlott** [comment]
I have the same errror since I´ve revived my console two weeks ago.

**Comment by UsernameTaken017** [comment]
Same issue here, plus this error also occurs on the wii u chat app

**Comment by Edi1977** [comment]
I have the same problem! Can anyone help for this?

**Comment by Butterscotch96** [comment]
Same error when changing user info.

**Comment by jonbarrow** [comment]
Updating user information on the Wii U was not released until very recently. You could update the information on the 3DS already, but not the Wii U. This is now supported.

**Comment by Butterscotch96** [comment]
I'm still getting the error. Do I need to update anything on my console?

**Comment by jonbarrow** [comment]
Yes. You need to update to the latest release of our patches. We released patch updates along with the server updates in this case
