### ISSUE TITLE
Pretendo (Connected) Pretendo (Using) 

### ISSUE THREAD

**Issue by NatsuDragneel808** [PretendoNetwork/.github#59]
This is another problem that I searched the Internet far and wide for but got no answers on and it's actually when I first installed the Pretendo plugin. Of course per usual, Pretendo still works on some stuff (Once again, thank you devs), I have come to the understanding that my notification should state "Connected to Pretendo Network" but it doesn't matter if my plugin is set to true or false. It always says "Using Pretendo Network". Now this isn't a big deal because again, pretendo works to connect to some games and stuff online but it also caused a lot of confusion for me when I first started and I had just assumed it didn't work for several days until I ended up attempting to play Mario kart 8 online and realized it did work, it just didn't state what it was supposed to when I was connected.

**Comment by jonbarrow** [comment]
This is not the correct repo for this. It sounds like you have some issue with either Inkay or the docs. But it's also such a non-issue I'm not even really sure what you're talking about.
