### ISSUE TITLE
Images and color break while using juxt

### ISSUE THREAD

**Issue by Giorgio2012** [PretendoNetwork/.github#61]
While im using juxt, It casually breaks the images and color
![20240421_152744](https://github.com/PretendoNetwork/Pretendo/assets/141070707/cc23788c-eef7-41db-9b55-ebde16c77e9a)
Is there any way to stop It from doing that?

**Comment by jonbarrow** [comment]
This is not the correct repository for this. If you are still having this issue, please report it on the https://github.com/PretendoNetwork/juxtaposition-ui repository
