### ISSUE TITLE
SSSL method broken

### ISSUE THREAD

**Issue by RISC-VLIW** [PretendoNetwork/.github#66]
I'm sure you are aware of the issue surrounding the SSSL method not working with splatoon, causing an error code listed below:

"104-0265"

There was an announcement in the discord server on the describing the issue and why it happens, but it's only based off of theories as far as I know, I am writing this issue to make sure this is known, and to perhaps know more details on it to easier help other's understand why this issue happens, and if it's an issue that can't be fixed code side, if suggesting people mod their wii u to use pretendo is the only method of fixing this issue, thank you very much!

**Comment by jonbarrow** [comment]
Closing as SSSL has been working for a while now
