### ISSUE TITLE
3ds takes longer time to turn off

### ISSUE THREAD

**Issue by Adnan12349** [PretendoNetwork/.github#68]
It seems badges on Pretendo Network are broken, I injected my own badges using GYTB, and since after that, I started experiencing long time shutdowns, which sometime took over a minute but after turning 3ds back on all the badges vanished, however the issue persist.

My console still takes longer time than usual to turn off, I'm using a New 3ds XL.

**Comment by Adnan12349** [comment]
I could be wrong but I have no clue why it's taking longer to turn off...

**Comment by jonbarrow** [comment]
This is not an issue with Pretendo, if you're experiencing issues after using homebrew you should contact that homebrews maintainer
