### ISSUE TITLE
[Bug]: error code 101-0502

### ISSUE THREAD

**Issue by Kwgaming215** [PretendoNetwork/.github#75]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What happened?

So I am trying to login to Mario Kart 8 for 2 days in a row and I keep getting error code 101-0502

### What did you expect to happen?

It connects

**Comment by jonbarrow** [comment]
Not only is this not the right repository for this sort of error (it's an error from the friends server), you should be using the support forum for general support https://forum.pretendo.network/c/support

**Comment by Kwgaming215** [comment]
But when do you think this will be fixed?

**Comment by jonbarrow** [comment]
As I said, this is not the correct place for support. I linked to our support forum. Our support forum *already* has posts about this.
