### ISSUE TITLE
Add inapp login feature

### ISSUE THREAD

**Issue by ADev531** [PretendoNetwork/.github#76]
### Checked Existing

- [x] I have checked the repository for duplicate issues.

### What feature do you want to see added?

In app pretendo login in nimbus

### Why do you want to have this feature?

The Korean firmware doesn't have login button in settings.

### Any other details to share? (OPTIONAL)

Many Korean players wants pretendo network including me, please add it.

**Comment by jonbarrow** [comment]
This is the wrong repository to ask this. Also it's not as simple as "just add logging in". If the Korean firmware isn't made for NNIDs then it's possible large chunks of functionality are just missing which wouldn't be trivial to replace, especially *just* within Nimbus.

Please use the correct repository for making feature requests.
