### ISSUE TITLE
[Feature]: new soup weegee you

### ISSUE THREAD

**Issue by SpareEnderboy** [PretendoNetwork/.github#77]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

New Super Luigi U Miiverse posting functionality

### Why do you want to have this feature?

NSLU already allowed posting to miiverse (found out on a stream lol) but it didn't work on the stream. The streamer has been confirmed by me to be using pretendo.

**Comment by jonbarrow** [comment]
This is not the correct repository for this. Please use the appropriate repository
