### ISSUE TITLE
[Feature]: Minecraft: Wii U Edition Support

### ISSUE THREAD

**Issue by EditDungeon** [PretendoNetwork/.github#84]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What feature do you want to see added?

Network support for Minecraft: Wii U Edition (ex. Minigames, Multiplayer worlds)

### Why do you want to have this feature?

So I can keep playing online minigames in Minecraft: Wii U Edition

**Comment by MatthewL246** [comment]
Minecraft: Wii U Edition is already supported and publicly available!

See https://github.com/PretendoNetwork/minecraft-wiiu.
