### ISSUE TITLE
[Feature]: Animal Crossing New Leaf 3DS

### ISSUE THREAD

**Issue by Pro597Pretendo** [PretendoNetwork/.github#85]
### Checked Existing

- [ ] I have checked the repository for duplicate issues.

### What feature do you want to see added?

create the online for the 3ds new leaf game

### Why do you want to have this feature?

Due to being a popular game and one in which many people spent their childhood on Tortimer Island taking tours or inviting their friends to their towns, I consider it necessary to work on making this possible.

**Comment by jonbarrow** [comment]
All games which use Nintendo Network are planned for support. Please do not make issues requesting specific games, they will come when they come
