### ISSUE TITLE
Pokemon bank Error 

### ISSUE THREAD

**Issue by Someonelastname** [PretendoNetwork/.github#86]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What would you like to know?

Pokemon bank keeps giving me an error code 022-2482 and I was wondering how to fix it. Is there anything I can do?

**Comment by jonbarrow** [comment]
This is not the right place for asking these questions. This repo is not meant for issues like this. We have a forum and a Discord where you can ask this, and a Discord bot which gives detailed info on error codes.

Pokemon Bank isn't a title we support. Hence the error.
