### ISSUE TITLE
Teams are TRASH

### ISSUE THREAD

**Issue by Pinuaple** [PretendoNetwork/.github#89]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

im tired of being always in the bad team, there is ALWAYS 3 S RANKS ON THE OTHER TEAM WHILE IM HERE WITH MY 3 C RANKS LOOSING ALL THE TIME, IM TIRED IM REALLY TIRED PLEAS FIX THIS, ALL I DO IS LOOSING RANK AND GETTING **BORED** EXTREMELY BORED OF LOOSING ALL THE TIME
pls pretendo i love u fix this

**Comment by MatthewL246** [comment]
Completely irrelevant to this repo
