### ISSUE TITLE
Same plugin for all on demand services

### ISSUE THREAD

**Issue by Luis9024** [PretendoNetwork/.github#90]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What would you like to know?

Can you make the same plugin, but for Netflix, Hulu, Amazon Instant Video, Napster/Rhapsody, Watchup, and Crunchyroll?

**Comment by jonbarrow** [comment]
This is a metadata repo. All new issues should be made on the correct service repo. It's also not really clear what you're asking for here

**Comment by Luis9024** [comment]
I'm asking if you can revive those other streaming services with that same kind of plugin, like for example: GiveMiiHulu.wps, GiveMiiNetflix.wps, and GiveMiiAmazon.wps.

**Comment by MatthewL246** [comment]
No, because those are paid services and most likely have additional DRM that would cause issues.

**Comment by Luis9024** [comment]
Will they ever be revived?
